import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql


revision = "4d42cf3d11de"
down_revision = "1876f90b58e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flag",
        sa.Column("created_timestamp", postgresql.TIMESTAMP(), nullable=True),
    )
    op.add_column(
        "flag",
        sa.Column("reported_timestamp", postgresql.TIMESTAMP(), nullable=True),
    )
    op.add_column(
        "value",
        sa.Column("created_timestamp", postgresql.TIMESTAMP(), nullable=True),
    )
    op.add_column(
        "value",
        sa.Column("reported_timestamp", postgresql.TIMESTAMP(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("value", "reported_timestamp")
    op.drop_column("value", "created_timestamp")
    op.drop_column("flag", "reported_timestamp")
    op.drop_column("flag", "created_timestamp")
    # ### end Alembic commands ###
