import sqlalchemy as sa

from alembic import op



revision = 'a327a3ea7a5f'
down_revision = '4d42cf3d11de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('flag_name_idx', 'flag', ['name'], unique=False)
    op.create_index('value_name_idx', 'value', ['name'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('value_name_idx', table_name='value')
    op.drop_index('flag_name_idx', table_name='flag')
    # ### end Alembic commands ###
