version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  commands:
    - pip install pdm==2.24.2
    - pdm sync -G dev -G docs
    - pdm run docs
    - mkdir -p _readthedocs
    - mv docs/build _readthedocs/html
