logging:
  level_app: debug
  level_libs: debug
  handlers: [console]

  syslog_app: null
  syslog_facility: null
  syslog_mapping: null
  syslog_defaults: null

postgres:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  database: featureflags

debug: true
secret: 023517f06f444118986877e636b4a226

ldap:
  host: null
  base_dn: cn=$user,ou=People,dc=acme,dc=com
