version: "3.8"

services:
  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: featureflags
    volumes:
      - "pg-data:/var/lib/postgresql/data"
    networks:
      - main

  backend: &backend
    image: featureflags-server
    user: ${CURRENT_UID}
    environment: &env
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PYTHONIOENCODING: UTF-8
      PYTHONPATH: server:client:protobuf
      PYTHONUNBUFFERED: 1
    networks:
      - main
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - ./protobuf:/app/protobuf
      - ./scripts:/app/scripts
      - ./config.yaml:/app/config.yaml

  web:
    <<: *backend
    init: true
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command:
    - bash
    - c
    - |
      if [[ ! -d server/
      pdm run watchfiles --filter python "python3 -m featureflags.server config.yaml web --port 8000" server

  rpc:
    <<: *backend
    init: true
    depends_on:
      - postgres
    ports:
      - "50051:50051"
    command: pdm run watchfiles --filter python "python3 -m featureflags.server config.yaml rpc --port 50051" server

  test:
    <<: *backend
    image: featureflags-server-test
    init: true
    depends_on:
      - postgres
    environment:
      <<: *env
      PYTHONPATH: "server:client:protobuf"
    command:
      - sh
      - -c
      - |
        /app/scripts/wait-for-it.sh -h postgres -p 5432;
        pdm run test ${ARGS}

  docs:
    <<: *backend
    image: featureflags-docs
    environment:
      <<: *env
      PYTHONPATH: client:server:protobuf
    command: sphinx-build -a -b html docs public

volumes:
  pg-data:
    driver: local

networks:
  main:
    driver: bridge
