version: "3.8"

services:
  postgres:
    image: timescale/timescaledb:0.9.1-pg10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: featureflags
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - main

  backend: &backend
    image: featureflags-server
    environment: &env
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PYTHONIOENCODING: UTF-8
      PYTHONPATH: server
      PYTHONUNBUFFERED: 1
    networks:
      - main

  web:
    <<: *backend
    init: true
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: watchexec --restart -w server --exts py -- python3 -m featureflags.server config.yaml@local web --port 8000

  rpc:
    <<: *backend
    init: true
    depends_on:
      - postgres
    ports:
      - "50051:50051"
    volumes:
      - ./:/app
    command: python3 -m featureflags.server config.yaml@local rpc --port 50051

  test:
    <<: *backend
    image: featureflags-server-test
    init: true
    environment:
      <<: *env
      PYTHONPATH: server:client
    volumes:
      - ./:/app
    command: py.test

volumes:
  db-data:
    driver: local

networks:
  main:
    driver: bridge
