from alembic import op


revision = "8df4e7dd1897"
down_revision = "33ace31b89cc"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("SET timescaledb.allow_install_without_preload = 'on';")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("changelog_flag_fkey", "changelog", type_="foreignkey")
    op.create_foreign_key(
        "changelog_flag_fkey",
        "changelog",
        "flag",
        ["flag"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "changelog", type_="foreignkey")
    op.create_foreign_key(
        "changelog_flag_fkey", "changelog", "flag", ["flag"], ["id"]
    )
    # ### end Alembic commands ###
