debug: true
secret: 023517f06f444118986877e636b4a226
test_environ: true

app:
  port: 8000
  host: 0.0.0.0
  reload: True

http:
  port: 8080
  host: 0.0.0.0
  reload: True

rpc:
  port: 50051
  host: 0.0.0.0

logging:
  level_app: debug
  level_libs: info
  handlers: [console]
  syslog_app: null
  syslog_facility: null
  syslog_mapping: null
  syslog_defaults: null

postgres:
  host: postgres-test
  port: 5432
  database: featureflags-test
  timeout: 10

ldap:
  host: null
  base_dn: null

instrumentation:
  prometheus_port: null
