# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from featureflags.protobuf import service_pb2 as featureflags_dot_protobuf_dot_service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FeatureFlagsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.exchange = channel.unary_unary(
        '/featureflags.service.FeatureFlags/exchange',
        request_serializer=featureflags_dot_protobuf_dot_service__pb2.ExchangeRequest.SerializeToString,
        response_deserializer=featureflags_dot_protobuf_dot_service__pb2.ExchangeReply.FromString,
        )
    self.Exchange = channel.unary_unary(
        '/featureflags.service.FeatureFlags/Exchange',
        request_serializer=featureflags_dot_protobuf_dot_service__pb2.ExchangeRequest.SerializeToString,
        response_deserializer=featureflags_dot_protobuf_dot_service__pb2.ExchangeReply.FromString,
        )
    self.store_stats = channel.unary_unary(
        '/featureflags.service.FeatureFlags/store_stats',
        request_serializer=featureflags_dot_protobuf_dot_service__pb2.StoreStatsTask.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.StoreStats = channel.unary_unary(
        '/featureflags.service.FeatureFlags/StoreStats',
        request_serializer=featureflags_dot_protobuf_dot_service__pb2.StoreStatsTask.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class FeatureFlagsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def exchange(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Exchange(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def store_stats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StoreStats(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FeatureFlagsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'exchange': grpc.unary_unary_rpc_method_handler(
          servicer.exchange,
          request_deserializer=featureflags_dot_protobuf_dot_service__pb2.ExchangeRequest.FromString,
          response_serializer=featureflags_dot_protobuf_dot_service__pb2.ExchangeReply.SerializeToString,
      ),
      'Exchange': grpc.unary_unary_rpc_method_handler(
          servicer.Exchange,
          request_deserializer=featureflags_dot_protobuf_dot_service__pb2.ExchangeRequest.FromString,
          response_serializer=featureflags_dot_protobuf_dot_service__pb2.ExchangeReply.SerializeToString,
      ),
      'store_stats': grpc.unary_unary_rpc_method_handler(
          servicer.store_stats,
          request_deserializer=featureflags_dot_protobuf_dot_service__pb2.StoreStatsTask.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'StoreStats': grpc.unary_unary_rpc_method_handler(
          servicer.StoreStats,
          request_deserializer=featureflags_dot_protobuf_dot_service__pb2.StoreStatsTask.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'featureflags.service.FeatureFlags', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
