name: Build & publish

on:
  push:
    tags:
    - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install lets
      uses: lets-cli/lets-action@v1.1

    - name: Set up Node
      uses: actions/setup-node@v4.0.1
      with:
        node-version: 20
        cache-dependency-path: ./ui/package-lock.json
        cache: 'npm'

    - name: Install dependencies
      working-directory: ./ui
      run: npm install

    - name: Build UI and copy bundle
      working-directory: ./ui
      run: npm run build -- --outDir ../featureflags/web/static

    - name: Set up Python with PDM ${{ matrix.python-version }}
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}
        version: 2.18.0

    - name: Upload package to pypi.org
      run: pdm publish -u "__token__" -P ${{ secrets.PYPI_TOKEN }}
