name: Build & publish

on:
  push:
    tags:
    - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python with PDM ${{ matrix.python-version }}
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build and copy UI bundle
      run: ./scripts/build-copy-ui-dist.sh

    - name: Upload package to pypi.org
      run: pdm publish -u "__token__" -P ${{ secrets.PYPI_TOKEN }}
