name: Test

on:
  pull_request:
    branches:
      - main
      - migrate-to-http-client
    types:
      - assigned
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install lets
        uses: lets-cli/lets-action@v1.1

      - name: Set up Node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20
          cache-dependency-path: ./ui/package-lock.json
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./ui
        run: npm install

      - name: Build UI
        run: lets build-copy-ui-bundle

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run server tests
        run: lets test
