name: Test

# TODO: enable after test fixes
on: workflow_dispatch
#  pull_request:
#    branches:
#      - main
#    types:
#      - assigned
#      - opened
#      - synchronize
#      - reopened

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install lets
        uses: lets-cli/lets-action@v1.1
      - name: Run test
        run: lets test server
