name: Test

on:
  pull_request:
    branches:
      - main
      - migrate-to-http-client
    types:
      - assigned
      - opened
      - synchronize
      - reopened

jobs:
  test-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install lets
        uses: lets-cli/lets-action@v1.1

      - name: Run test
        run: lets test
