name: Test
on:
  pull_request:
    branches:
      - main
    types:
      - assigned
      - opened
      - synchronize
      - reopened

jobs:
  test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", 3.11]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install tox tox-gh-actions tox-pdm
      - name: Test with tox
        run: |
          tox --version
          tox

  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install lets
        uses: lets-cli/lets-action@v1.1
      - name: Run test
        run: lets test server
